preset: recommended

linting: true

enabled:
  - short_array_syntax
  - strict
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - long_array_syntax

finder:
  name:
    - "*.php"
  path:
    - "module"
