preset: recommended

linting: true

enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - short_array_syntax
  - header_comment

finder:
  exclude:
    - "module/*/test"
  name:
    - "*.php"
  path:
    - "module"
