language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

install:
  - sudo apt-get install parallel
  - sudo apt-get install nodejs npm
  - npm install -g bower
  - /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer self-update
  - travis_retry composer install
  - bower install

before_script:
  - mkdir -p build/coverage
  - mkdir -p build/logs
  - mysql -e 'create database IF NOT EXISTS learnzf2;' -uroot
  - cp config/autoload/doctrine.local.php.dist config/autoload/doctrine.local.php
  - php vendor/bin/doctrine-module migrations:migrate --no-interaction
  - php -S localhost:8000 -t public/ &
  - vendor/bin/phantomjs --webdriver=4444 && PID=$! &
  - sleep 1

script:
  - ls -d module/*/test/PHPUnit | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c {}/phpunit.xml;' || exit 1
  - cd module && for i in $(ls -d *); do ./../vendor/bin/codecept --config=${i%%/}/test/Codeception/codeception.yml run acceptance; done
  - cd ..

after_script:
  - php coverage-report.php
  - php vendor/bin/coveralls -v --exclude-no-stmt

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
