language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - sudo apt-get install parallel
  - composer install --dev --prefer-source

script:
  - ls -d module/* | parallel --gnu --keep-order 'echo "Running {} CS checks"; ./vendor/bin/php-cs-fixer fix {} -v --dry-run --config-file=.php_cs;' || exit 1
  - mkdir -p build/coverage
  - phpunit --coverage-clover build/coverage/clover-application.xml --configuration module/Application/test/phpunit.xml module/Application/test/ApplicationTest/

after_script:
  # todo ? : Merges the individual clover reports of each component into a single clover.xml
  - php vendor/bin/coveralls -v

after_success:
  coveralls

notifications:
  email: false

matrix:
  fast_finish: true
