language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - sudo apt-get install parallel
  - composer install --dev --prefer-source

script:
  - phpunit --configuration module/Application/test/phpunit.xml module/Application/test/ApplicationTest/

notifications:
  email: false
