language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - sudo apt-get install parallel
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - ls -d module/* | parallel --gnu --keep-order 'echo "Running {} CS checks"; ./vendor/bin/php-cs-fixer fix {} -v --dry-run --config-file=.php_cs;' || exit 1
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false

matrix:
  fast_finish: true
